version: '3.8'
services:
  context-matcher-database:
    image: postgres:latest
    network_mode: bridge
    container_name: context-matcher-database
    expose:
      - 5439
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=context-matcher
    restart: unless-stopped